<?php

namespace Tpfilrouge\skillsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * competenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class competenceRepository extends EntityRepository
{
}
