parameters:
#    tpfilrougeskills.example.class: Tpfilrouge\skillsBundle\Example

services:
#    tpfilrougeskills.example:
#        class: %tpfilrougeskills.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
