parameters:
#    imie_skills.example.class: Imie\SkillsBundle\Example

services:
#    imie_skills.example:
#        class: %imie_skills.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
